### PR TITLE
Add helper for setting key

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR adds convenient functions to set key signatures.

```cpp
void makeKeySignature (int fifths, bool mode = 0);
```

Similar to the `addTimeSignature` this PR adds an easy way to add a key signature meta event to a MIDI file: 

```cpp
MidiEvent* addKeySignature (int aTrack, int aTick, int key, bool mode = 0);
```
The `fifths` parameter specifies the position within the circle of fifths, the `mode` parameter specifies if this is a minor key.

In the following case we add a D major key to track 2 and a G minor to track 3: 
```cpp
addKeySignature(1, 0, 2, 0}
addKeySignature(2, 0, -2, 1}
```

image

When opening this in MuseScore, it will read this information and render accordingly:
image

NB: MIDI only differentiates between _major_ and _minor_, that's why a boolean is used as forth parameter. It is major by default.

### CODE REVIEW

**Comment by rettinghaus** [comment]
@craigsapp Have you ever noticed this PR?

**Comment by wherefree** [comment]
您好，您所发送的邮件我已收到。

**Comment by rettinghaus** [comment]
@craigsapp I just remembered this PR. How about merging?

**Comment by wherefree** [comment]
您好，您所发送的邮件我已收到。

**Pull request merged**
